version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=your_secret_key
      - APP_DATABASE=postgresql://postgres_username:postgres_password@db:5432/app_database_name
      - TEST_DATABASE=postgresql://postgres_username:postgres_password@db:5432/test_database_name
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres_username
      - POSTGRES_PASSWORD=postgres_password
